# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72e206b3e15aaa191bfbfc0975f9f0040810ee81e0bba117d77832c9ae938cf8efc75d2dfcb2925e8f3c2bdf2691d7e42eaeb86da998406557d8d864907e0547

test:
  secret_key_base: 917e455c27b980a97ae33b57b07d1eda81af5d0191a7647dd91236a52582446c77564a6a46b3b2ba0fe54bbddfc73cf985f4350bb3f7b05b740265db507c01c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
